language: node_js
node_js:
- "6"
services:
  - mongodb
env:
  - NODE_ENV=test

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});' 
script: npm test
