language: node_js
node_js:
- "6"
services:
  - mongodb
sudo: false
env:
 - NODE_ENV=test
  global:
    - MONGODB_VERSION=2.6.10
install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 3


before_script:
  - sleep 15
  - mongo
script:
  - mongo --eval 'db.hostInfo()'
  - npm test
